### ISSUE TITLE
A missing test case from toml-test

### ISSUE THREAD

**Issue by gyfis** [mame/perfect_toml#1]
First of all, thanks for publishing the library, the simplicity of code and performance is very impressive and inspiring! 👏 

When comparing to the other Ruby implementations (https://github.com/gyfis/toml-comparison), I found that the current implementation doesn't pass on a single `toml-test` case:

- https://github.com/BurntSushi/toml-test/blob/master/tests/invalid/control/comment-null.toml

```
irb(main):004:0> data = 'comment-null = "null" # '
=> "comment-null = \"null\" # "
irb(main):005:0> PerfectTOML.parse(data)
=> {"comment-null"=>"null"}
```

Quite an edge case bu wanted to raise these nevertheless.

Take care! 👋

**Comment by mame** [comment]
Thank you for playing with PerfectTOML!

On my machine, the test case raises a `PerfectTOML::ParseError` as expected.

```
$ wget https://github.com/BurntSushi/toml-test/raw/master/tests/invalid/control/comment-null.toml

$ irb -rperfect_toml
$ irb -rperfect_toml
irb(main):001:0> PerfectTOML.load_file("comment-null.toml")
/home/mame/local/lib/ruby/gems/3.1.0/gems/perfect_toml-0.9.0/lib/perfect_toml.rb:327:in `error': unexpected character found: "\x00" at line 1 column 25 (PerfectTOML::ParseError)
...
```

Maybe a NUL character is accidentally dropped when you copy/paste the TOML data?

**Comment by gyfis** [comment]
> Thank you for playing with PerfectTOML!
> 
> On my machine, the test case raises a `PerfectTOML::ParseError` as expected.
> 
> ```
> $ wget https://github.com/BurntSushi/toml-test/raw/master/tests/invalid/control/comment-null.toml
> 
> $ irb -rperfect_toml
> irb(main):001:0> PerfectTOML.load_file("comment-null.toml")
> /home/mame/local/lib/ruby/gems/3.1.0/gems/perfect_toml-0.9.0/lib/perfect_toml.rb:327:in `error': unexpected character found: "\x00" at line 1 column 25 (PerfectTOML::ParseError)
> ...
> ```
> 
> Maybe a NUL character is accidentally dropped when you copy/paste the TOML data?

Apologies, that must’ve been the case! Sorry for the extra issue 🤦
